site_name: MongoDB Data Source
theme:
  name: material
  language: en
  features:
    - content.code.copy
repo_url: https://github.com/haohanyang/mongodb-datasource
site_url: https://haohanyang.github.io/mongodb-datasource/
site_author: Haohan Yang
site_description: Documentation for MongoDB Data Source for Grafana
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - 'Get Started': get-started.md
  - 'Changelog': changelog.md
  - Configuration: configs.md
  - Query: query.md
  - 'Gloabal and Plugin Variables': global-and-plugin-variables.md
  - 'Query Variable': query-variable.md
  - 'Code Editor': code-editor.md
  - 'Supported BSON Types': 'supported-bson-types.md'
extra_javascript:
  - javascripts/main.bundle.js
