# This GitHub Action automates the process of building Grafana plugins.
# (For more information, see https://github.com/grafana/plugin-actions/blob/main/build-plugin/README.md)
name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27018:27017
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-plugin
        with:
          go-version: '1.23.0'
        # Uncomment to enable plugin signing
        # (For more info on how to generate the access policy token see https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token)
        #with:
        # Make sure to save the token in your repository secrets
        #policy_token: $
        # Usage of GRAFANA_API_KEY is deprecated, prefer `policy_token` option above
        #grafana_token: $
